version: '2.2'
services:
  postgres:
    restart: always
    image: "postgres:11"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - dataPg:/var/lib/postgresql/data
    networks:
      - networkName

  mytbpe:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "9090:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - networkName

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - networkName

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3030:3000
    networks:
      - networkName
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - networkName
    volumes:
      - dataPg:/var/lib/node_red/data
volumes:
  dataPg:
networks:
  networkName: